### ISSUE TITLE
Eye state being locked

### ISSUE THREAD

**Issue by cpaca** [PhantomOwl404/Desktop-Awoo#33] opened 2019-07-06 05:42 UTC
Basically: If you cause something that causes the eye to look different, then click on the eye, it'll be fixed in that state until you do something to change it.  
  
This is easy to replicate by clicking her mouth (AWOO), which causes her to go >.< mode. Then, clicking on the eye will make her mad (as expected) then both animations will end, but she will still be in >.< mode.
This is also replicable by putting the mouse over the head (for star-eyes) then clicking on the eyes as fast as possible. (Too slowly and she resets to her normal, expected eye state)

**Comment by PhantomOwl404** [comment] 2019-07-20 13:54
Thanks for the look out. The issue is fixed now.

**Closed by PhantomOwl404** 2019-07-20 13:54 UTC
